#!/usr/bin/python
# -*- coding: utf-8 -*-

import os
import sys
import math
import shutil
import tempfile
import time
# Try to import gnuplot for line plot output. If not on the system, set a flag to supress this output
# You will need the python-gnuplot package for this
noGnuplot = False
try:
    import Gnuplot
except ImportError:
    noGnuplot = True

# set parameters
procs = 1  # number of MPI procs to be used
N_max = 10 # biggest polynomial degree to be used

from modify_prm import modify_prm, read_prm
from analyze_functions import get_last_L2_error, get_last_Linf_error
from execute_flexi import execute_flexi

tflexi = "./flexi_" + str(int(time.time()))
if len(sys.argv) == 2 :
   flexi_path = "../../build/bin/flexi"
   if not os.path.exists(flexi_path) :
      print "path to flexi-executable '%s' is wrong, please modify script" % \
            flexi_path
      print "or use './convergence.py [path to flexi-executable] prm-file'"
      sys.exit(1)
   prm_path = sys.argv[1]
elif len(sys.argv) == 3 :
   flexi_path = sys.argv[1]
   prm_path = sys.argv[2]
else :
   print 'usage: ./convergence.py [path to flexi-executable] prm-file'
   sys.exit(1)

if not os.path.exists(prm_path) :
   print "parameter-file '%s' not found" % prm_path 
   sys.exit(1)

shutil.copy(flexi_path, tflexi)
time.sleep(1.0)
flexi_path = tflexi

# modify nElems of Grid in X and Y direction
modify_prm(prm_path, {'MeshFile' : '../../ini/convtest/CART_HEX_PERIODIC_004_mesh.h5'})

tprm = tempfile.NamedTemporaryFile()
shutil.copy(prm_path, tprm.name)

for line in open(tprm.name, 'r').readlines() :
   print line,

# get ProjectName
projectname = str(read_prm(prm_path,'ProjectName'))
# create filename for Gnuplot
filename = projectname+"_convtest_N.pdf"
shutil.copy(prm_path,filename)

# open file to print order of convergence
convfile = projectname+'_convfile_N.csv'
shutil.copy(prm_path,convfile)
f = open(convfile,'w')

L2_array = [[] for i in range(1,N_max+1)]
x_array  = [i for i in range(1,N_max+1)]
i=0
for N in range(1,N_max+1) :
   i = i + 1

   # modify polynomial degree
   modify_prm(prm_path, {'N' : N})
   # save last L2, Linf error for EOC computation
   if i > 1 :
      last_L2 = L2
      last_Linf = Linf

   start_time = time.time()
   # execute flexi and get L2, L_inf error
   L2, Linf = execute_flexi(flexi_path, prm_path, projectname, \
         [get_last_L2_error, get_last_Linf_error], mpi_procs = procs)
   end_time = time.time()

   # output header of output-table
   if i == 1:
      sys.stdout.write("═════╦")
      for j in range(len(L2))  :
         sys.stdout.write("═══════════════════════════════════════════╦")
      sys.stdout.write('\n')
      print " N   ║",
      for j in range(len(L2))  :
         sys.stdout.write(" L2 err      EOC     | Linf err    EOC     ║")
      sys.stdout.write('\n')
      sys.stdout.write("═════╬")
      for j in range(len(L2))  :
         sys.stdout.write("═══════════════════════════════════════════╬")
      sys.stdout.write('\n')
   print " %02d  ║" % N,

   # output L2, Linf errors and EOC
   for j in range(len(L2))  :
      if i == 1 :
        conv_l2 = -99.
        conv_linf = -99.
      else :
        try :
          conv_l2 = math.log(last_L2[j]/L2[j]) / math.log(float(N+1)/float(last_N))
          conv_linf = math.log(last_Linf[j]/Linf[j]) / math.log(float(N+1)/float(last_N))
        except :
           conv_l2 = -99
           conv_linf = -99
      print "%8.4e %8.4f | %8.4e %8.4f ║" % (L2[j], conv_l2,\
            Linf[j],  conv_linf),
   L2_array[i-1] = L2[1]
   print end_time - start_time
   sys.stdout.flush()
   last_N = N+1


if noGnuplot != True:
   g = Gnuplot.Gnuplot()
   g.title('ConvTest X-Momentum')
   g.xlabel('Polynomial Degree')
   g.ylabel('L2 Error')
   g('set logscale xy')
   g('set terminal pdf')
   g('set output "'+filename+'"')
   gnuplot_data = Gnuplot.Data(x_array,L2_array,with_="line")
   g('exact(x)=(1./x)**x')
   g.plot(gnuplot_data,'exact(x)')

f.close()
os.remove(flexi_path)         
